// This file is generated automatically with 'npm run generate-icons' script
import ActivityGlyph from '@atlaskit/icon/svgs/activity.svg';
import AddCircleGlyph from '@atlaskit/icon/svgs/add-circle.svg';
import AddItemGlyph from '@atlaskit/icon/svgs/add-item.svg';
import AddGlyph from '@atlaskit/icon/svgs/add.svg';
import AddonGlyph from '@atlaskit/icon/svgs/addon.svg';
import AppAccessGlyph from '@atlaskit/icon/svgs/app-access.svg';
import AppSwitcherGlyph from '@atlaskit/icon/svgs/app-switcher.svg';
import ArrowDownCircleGlyph from '@atlaskit/icon/svgs/arrow-down-circle.svg';
import ArrowDownGlyph from '@atlaskit/icon/svgs/arrow-down.svg';
import ArrowLeftCircleGlyph from '@atlaskit/icon/svgs/arrow-left-circle.svg';
import ArrowLeftGlyph from '@atlaskit/icon/svgs/arrow-left.svg';
import ArrowRightCircleGlyph from '@atlaskit/icon/svgs/arrow-right-circle.svg';
import ArrowRightGlyph from '@atlaskit/icon/svgs/arrow-right.svg';
import ArrowUpCircleGlyph from '@atlaskit/icon/svgs/arrow-up-circle.svg';
import ArrowUpGlyph from '@atlaskit/icon/svgs/arrow-up.svg';
import AttachmentGlyph from '@atlaskit/icon/svgs/attachment.svg';
import AudioCircleGlyph from '@atlaskit/icon/svgs/audio-circle.svg';
import AudioGlyph from '@atlaskit/icon/svgs/audio.svg';
import BacklogGlyph from '@atlaskit/icon/svgs/backlog.svg';
import BillingFilledGlyph from '@atlaskit/icon/svgs/billing-filled.svg';
import BillingGlyph from '@atlaskit/icon/svgs/billing.svg';
import BitbucketBranchesGlyph from '@atlaskit/icon/svgs/bitbucket/branches.svg';
import BitbucketBuildsGlyph from '@atlaskit/icon/svgs/bitbucket/builds.svg';
import BitbucketCloneGlyph from '@atlaskit/icon/svgs/bitbucket/clone.svg';
import BitbucketCommitsGlyph from '@atlaskit/icon/svgs/bitbucket/commits.svg';
import BitbucketCompareGlyph from '@atlaskit/icon/svgs/bitbucket/compare.svg';
import BitbucketForksGlyph from '@atlaskit/icon/svgs/bitbucket/forks.svg';
import BitbucketOutputGlyph from '@atlaskit/icon/svgs/bitbucket/output.svg';
import BitbucketPipelinesGlyph from '@atlaskit/icon/svgs/bitbucket/pipelines.svg';
import BitbucketPullrequestsGlyph from '@atlaskit/icon/svgs/bitbucket/pullrequests.svg';
import BitbucketReposGlyph from '@atlaskit/icon/svgs/bitbucket/repos.svg';
import BitbucketSnippetsGlyph from '@atlaskit/icon/svgs/bitbucket/snippets.svg';
import BitbucketSourceGlyph from '@atlaskit/icon/svgs/bitbucket/source.svg';
import BoardGlyph from '@atlaskit/icon/svgs/board.svg';
import BookGlyph from '@atlaskit/icon/svgs/book.svg';
import BulletListGlyph from '@atlaskit/icon/svgs/bullet-list.svg';
import CalendarFilledGlyph from '@atlaskit/icon/svgs/calendar-filled.svg';
import CalendarGlyph from '@atlaskit/icon/svgs/calendar.svg';
import CameraFilledGlyph from '@atlaskit/icon/svgs/camera-filled.svg';
import CameraRotateGlyph from '@atlaskit/icon/svgs/camera-rotate.svg';
import CameraTakePictureGlyph from '@atlaskit/icon/svgs/camera-take-picture.svg';
import CameraGlyph from '@atlaskit/icon/svgs/camera.svg';
import CanvasGlyph from '@atlaskit/icon/svgs/canvas.svg';
import CheckCircleOutlineGlyph from '@atlaskit/icon/svgs/check-circle-outline.svg';
import CheckCircleGlyph from '@atlaskit/icon/svgs/check-circle.svg';
import CheckGlyph from '@atlaskit/icon/svgs/check.svg';
import CheckboxIndeterminateGlyph from '@atlaskit/icon/svgs/checkbox-indeterminate.svg';
import CheckboxGlyph from '@atlaskit/icon/svgs/checkbox.svg';
import ChevronDownCircleGlyph from '@atlaskit/icon/svgs/chevron-down-circle.svg';
import ChevronDownGlyph from '@atlaskit/icon/svgs/chevron-down.svg';
import ChevronLeftCircleGlyph from '@atlaskit/icon/svgs/chevron-left-circle.svg';
import ChevronLeftLargeGlyph from '@atlaskit/icon/svgs/chevron-left-large.svg';
import ChevronLeftGlyph from '@atlaskit/icon/svgs/chevron-left.svg';
import ChevronRightCircleGlyph from '@atlaskit/icon/svgs/chevron-right-circle.svg';
import ChevronRightLargeGlyph from '@atlaskit/icon/svgs/chevron-right-large.svg';
import ChevronRightGlyph from '@atlaskit/icon/svgs/chevron-right.svg';
import ChevronUpCircleGlyph from '@atlaskit/icon/svgs/chevron-up-circle.svg';
import ChevronUpGlyph from '@atlaskit/icon/svgs/chevron-up.svg';
import ChildIssuesGlyph from '@atlaskit/icon/svgs/child-issues.svg';
import CodeGlyph from '@atlaskit/icon/svgs/code.svg';
import CommentGlyph from '@atlaskit/icon/svgs/comment.svg';
import ComponentGlyph from '@atlaskit/icon/svgs/component.svg';
import CopyGlyph from '@atlaskit/icon/svgs/copy.svg';
import CreditcardFilledGlyph from '@atlaskit/icon/svgs/creditcard-filled.svg';
import CreditcardGlyph from '@atlaskit/icon/svgs/creditcard.svg';
import CrossCircleGlyph from '@atlaskit/icon/svgs/cross-circle.svg';
import CrossGlyph from '@atlaskit/icon/svgs/cross.svg';
import DashboardGlyph from '@atlaskit/icon/svgs/dashboard.svg';
import DecisionGlyph from '@atlaskit/icon/svgs/decision.svg';
import DepartmentGlyph from '@atlaskit/icon/svgs/department.svg';
import DetailViewGlyph from '@atlaskit/icon/svgs/detail-view.svg';
import DiscoverFilledGlyph from '@atlaskit/icon/svgs/discover-filled.svg';
import DiscoverGlyph from '@atlaskit/icon/svgs/discover.svg';
import DocumentFilledGlyph from '@atlaskit/icon/svgs/document-filled.svg';
import DocumentGlyph from '@atlaskit/icon/svgs/document.svg';
import DocumentsGlyph from '@atlaskit/icon/svgs/documents.svg';
import DownloadGlyph from '@atlaskit/icon/svgs/download.svg';
import DragHandlerGlyph from '@atlaskit/icon/svgs/drag-handler.svg';
import DropboxGlyph from '@atlaskit/icon/svgs/dropbox.svg';
import EditFilledGlyph from '@atlaskit/icon/svgs/edit-filled.svg';
import EditGlyph from '@atlaskit/icon/svgs/edit.svg';
import EditorAddGlyph from '@atlaskit/icon/svgs/editor/add.svg';
import EditorAddonGlyph from '@atlaskit/icon/svgs/editor/addon.svg';
import EditorAdvancedGlyph from '@atlaskit/icon/svgs/editor/advanced.svg';
import EditorAlignCenterGlyph from '@atlaskit/icon/svgs/editor/align-center.svg';
import EditorAlignImageCenterGlyph from '@atlaskit/icon/svgs/editor/align-image-center.svg';
import EditorAlignImageLeftGlyph from '@atlaskit/icon/svgs/editor/align-image-left.svg';
import EditorAlignImageRightGlyph from '@atlaskit/icon/svgs/editor/align-image-right.svg';
import EditorAlignLeftGlyph from '@atlaskit/icon/svgs/editor/align-left.svg';
import EditorAlignRightGlyph from '@atlaskit/icon/svgs/editor/align-right.svg';
import EditorAttachmentGlyph from '@atlaskit/icon/svgs/editor/attachment.svg';
import EditorBackgroundColorGlyph from '@atlaskit/icon/svgs/editor/background-color.svg';
import EditorBoldGlyph from '@atlaskit/icon/svgs/editor/bold.svg';
import EditorBulletListGlyph from '@atlaskit/icon/svgs/editor/bullet-list.svg';
import EditorCloseGlyph from '@atlaskit/icon/svgs/editor/close.svg';
import EditorCodeGlyph from '@atlaskit/icon/svgs/editor/code.svg';
import EditorCollapseGlyph from '@atlaskit/icon/svgs/editor/collapse.svg';
import EditorDateGlyph from '@atlaskit/icon/svgs/editor/date.svg';
import EditorDecisionGlyph from '@atlaskit/icon/svgs/editor/decision.svg';
import EditorDividerGlyph from '@atlaskit/icon/svgs/editor/divider.svg';
import EditorDoneGlyph from '@atlaskit/icon/svgs/editor/done.svg';
import EditorEditGlyph from '@atlaskit/icon/svgs/editor/edit.svg';
import EditorEmojiGlyph from '@atlaskit/icon/svgs/editor/emoji.svg';
import EditorErrorGlyph from '@atlaskit/icon/svgs/editor/error.svg';
import EditorExpandGlyph from '@atlaskit/icon/svgs/editor/expand.svg';
import EditorFeedbackGlyph from '@atlaskit/icon/svgs/editor/feedback.svg';
import EditorFileGlyph from '@atlaskit/icon/svgs/editor/file.svg';
import EditorHelpGlyph from '@atlaskit/icon/svgs/editor/help.svg';
import EditorHintGlyph from '@atlaskit/icon/svgs/editor/hint.svg';
import EditorHorizontalRuleGlyph from '@atlaskit/icon/svgs/editor/horizontal-rule.svg';
import EditorImageBorderGlyph from '@atlaskit/icon/svgs/editor/image-border.svg';
import EditorImageResizeGlyph from '@atlaskit/icon/svgs/editor/image-resize.svg';
import EditorImageGlyph from '@atlaskit/icon/svgs/editor/image.svg';
import EditorIndentGlyph from '@atlaskit/icon/svgs/editor/indent.svg';
import EditorInfoGlyph from '@atlaskit/icon/svgs/editor/info.svg';
import EditorItalicGlyph from '@atlaskit/icon/svgs/editor/italic.svg';
import EditorLayoutThreeEqualGlyph from '@atlaskit/icon/svgs/editor/layout-three-equal.svg';
import EditorLayoutThreeWithSidebarsGlyph from '@atlaskit/icon/svgs/editor/layout-three-with-sidebars.svg';
import EditorLayoutTwoEqualGlyph from '@atlaskit/icon/svgs/editor/layout-two-equal.svg';
import EditorLayoutTwoLeftSidebarGlyph from '@atlaskit/icon/svgs/editor/layout-two-left-sidebar.svg';
import EditorLayoutTwoRightSidebarGlyph from '@atlaskit/icon/svgs/editor/layout-two-right-sidebar.svg';
import EditorLinkGlyph from '@atlaskit/icon/svgs/editor/link.svg';
import EditorMediaCenterGlyph from '@atlaskit/icon/svgs/editor/media-center.svg';
import EditorMediaFullWidthGlyph from '@atlaskit/icon/svgs/editor/media-full-width.svg';
import EditorMediaWideGlyph from '@atlaskit/icon/svgs/editor/media-wide.svg';
import EditorMediaWrapLeftGlyph from '@atlaskit/icon/svgs/editor/media-wrap-left.svg';
import EditorMediaWrapRightGlyph from '@atlaskit/icon/svgs/editor/media-wrap-right.svg';
import EditorMentionGlyph from '@atlaskit/icon/svgs/editor/mention.svg';
import EditorMoreGlyph from '@atlaskit/icon/svgs/editor/more.svg';
import EditorNoteGlyph from '@atlaskit/icon/svgs/editor/note.svg';
import EditorNumberListGlyph from '@atlaskit/icon/svgs/editor/number-list.svg';
import EditorOpenGlyph from '@atlaskit/icon/svgs/editor/open.svg';
import EditorOutdentGlyph from '@atlaskit/icon/svgs/editor/outdent.svg';
import EditorPanelGlyph from '@atlaskit/icon/svgs/editor/panel.svg';
import EditorPhotoGlyph from '@atlaskit/icon/svgs/editor/photo.svg';
import EditorQuoteGlyph from '@atlaskit/icon/svgs/editor/quote.svg';
import EditorRecentGlyph from '@atlaskit/icon/svgs/editor/recent.svg';
import EditorRedoGlyph from '@atlaskit/icon/svgs/editor/redo.svg';
import EditorRemoveGlyph from '@atlaskit/icon/svgs/editor/remove.svg';
import EditorSearchGlyph from '@atlaskit/icon/svgs/editor/search.svg';
import EditorSettingsGlyph from '@atlaskit/icon/svgs/editor/settings.svg';
import EditorStrikethroughGlyph from '@atlaskit/icon/svgs/editor/strikethrough.svg';
import EditorSuccessGlyph from '@atlaskit/icon/svgs/editor/success.svg';
import EditorTableDisplayOptionsGlyph from '@atlaskit/icon/svgs/editor/table-display-options.svg';
import EditorTableGlyph from '@atlaskit/icon/svgs/editor/table.svg';
import EditorTaskGlyph from '@atlaskit/icon/svgs/editor/task.svg';
import EditorTextColorGlyph from '@atlaskit/icon/svgs/editor/text-color.svg';
import EditorTextStyleGlyph from '@atlaskit/icon/svgs/editor/text-style.svg';
import EditorUnderlineGlyph from '@atlaskit/icon/svgs/editor/underline.svg';
import EditorUndoGlyph from '@atlaskit/icon/svgs/editor/undo.svg';
import EditorUnlinkGlyph from '@atlaskit/icon/svgs/editor/unlink.svg';
import EditorWarningGlyph from '@atlaskit/icon/svgs/editor/warning.svg';
import EmailGlyph from '@atlaskit/icon/svgs/email.svg';
import EmojiActivityGlyph from '@atlaskit/icon/svgs/emoji/activity.svg';
import EmojiAtlassianGlyph from '@atlaskit/icon/svgs/emoji/atlassian.svg';
import EmojiCustomGlyph from '@atlaskit/icon/svgs/emoji/custom.svg';
import EmojiEmojiGlyph from '@atlaskit/icon/svgs/emoji/emoji.svg';
import EmojiFlagsGlyph from '@atlaskit/icon/svgs/emoji/flags.svg';
import EmojiFoodGlyph from '@atlaskit/icon/svgs/emoji/food.svg';
import EmojiFrequentGlyph from '@atlaskit/icon/svgs/emoji/frequent.svg';
import EmojiKeyboardGlyph from '@atlaskit/icon/svgs/emoji/keyboard.svg';
import EmojiNatureGlyph from '@atlaskit/icon/svgs/emoji/nature.svg';
import EmojiObjectsGlyph from '@atlaskit/icon/svgs/emoji/objects.svg';
import EmojiPeopleGlyph from '@atlaskit/icon/svgs/emoji/people.svg';
import EmojiProductivityGlyph from '@atlaskit/icon/svgs/emoji/productivity.svg';
import EmojiSymbolsGlyph from '@atlaskit/icon/svgs/emoji/symbols.svg';
import EmojiTravelGlyph from '@atlaskit/icon/svgs/emoji/travel.svg';
import EmojiAddGlyph from '@atlaskit/icon/svgs/emoji-add.svg';
import EmojiGlyph from '@atlaskit/icon/svgs/emoji.svg';
import ErrorGlyph from '@atlaskit/icon/svgs/error.svg';
import ExportGlyph from '@atlaskit/icon/svgs/export.svg';
import FeedbackGlyph from '@atlaskit/icon/svgs/feedback.svg';
import FileGlyph from '@atlaskit/icon/svgs/file.svg';
import FilterGlyph from '@atlaskit/icon/svgs/filter.svg';
import FlagFilledGlyph from '@atlaskit/icon/svgs/flag-filled.svg';
import FolderFilledGlyph from '@atlaskit/icon/svgs/folder-filled.svg';
import FolderGlyph from '@atlaskit/icon/svgs/folder.svg';
import FollowersGlyph from '@atlaskit/icon/svgs/followers.svg';
import FollowingGlyph from '@atlaskit/icon/svgs/following.svg';
import GoogledriveGlyph from '@atlaskit/icon/svgs/googledrive.svg';
import GraphBarGlyph from '@atlaskit/icon/svgs/graph-bar.svg';
import GraphLineGlyph from '@atlaskit/icon/svgs/graph-line.svg';
import GsuiteGlyph from '@atlaskit/icon/svgs/gsuite.svg';
import HighlightsGlyph from '@atlaskit/icon/svgs/highlights.svg';
import HipchatAudioOnlyGlyph from '@atlaskit/icon/svgs/hipchat/audio-only.svg';
import HipchatChevronDoubleDownGlyph from '@atlaskit/icon/svgs/hipchat/chevron-double-down.svg';
import HipchatChevronDoubleUpGlyph from '@atlaskit/icon/svgs/hipchat/chevron-double-up.svg';
import HipchatChevronDownGlyph from '@atlaskit/icon/svgs/hipchat/chevron-down.svg';
import HipchatChevronUpGlyph from '@atlaskit/icon/svgs/hipchat/chevron-up.svg';
import HipchatDialOutGlyph from '@atlaskit/icon/svgs/hipchat/dial-out.svg';
import HipchatLobbyGlyph from '@atlaskit/icon/svgs/hipchat/lobby.svg';
import HipchatMediaAttachmentCountGlyph from '@atlaskit/icon/svgs/hipchat/media-attachment-count.svg';
import HipchatOutgoingSoundGlyph from '@atlaskit/icon/svgs/hipchat/outgoing-sound.svg';
import HipchatSdVideoGlyph from '@atlaskit/icon/svgs/hipchat/sd-video.svg';
import HomeCircleGlyph from '@atlaskit/icon/svgs/home-circle.svg';
import HomeFilledGlyph from '@atlaskit/icon/svgs/home-filled.svg';
import ImageBorderGlyph from '@atlaskit/icon/svgs/image-border.svg';
import ImageResizeGlyph from '@atlaskit/icon/svgs/image-resize.svg';
import ImageGlyph from '@atlaskit/icon/svgs/image.svg';
import InfoGlyph from '@atlaskit/icon/svgs/info.svg';
import InviteTeamGlyph from '@atlaskit/icon/svgs/invite-team.svg';
import IssueRaiseGlyph from '@atlaskit/icon/svgs/issue-raise.svg';
import IssueGlyph from '@atlaskit/icon/svgs/issue.svg';
import IssuesGlyph from '@atlaskit/icon/svgs/issues.svg';
import JiraCaptureGlyph from '@atlaskit/icon/svgs/jira/capture.svg';
import JiraFailedBuildStatusGlyph from '@atlaskit/icon/svgs/jira/failed-build-status.svg';
import JiraLabsGlyph from '@atlaskit/icon/svgs/jira/labs.svg';
import JiraTestSessionGlyph from '@atlaskit/icon/svgs/jira/test-session.svg';
import LabelGlyph from '@atlaskit/icon/svgs/label.svg';
import LightbulbFilledGlyph from '@atlaskit/icon/svgs/lightbulb-filled.svg';
import LightbulbGlyph from '@atlaskit/icon/svgs/lightbulb.svg';
import LikeGlyph from '@atlaskit/icon/svgs/like.svg';
import LinkFilledGlyph from '@atlaskit/icon/svgs/link-filled.svg';
import LinkGlyph from '@atlaskit/icon/svgs/link.svg';
import ListGlyph from '@atlaskit/icon/svgs/list.svg';
import LocationGlyph from '@atlaskit/icon/svgs/location.svg';
import LockCircleGlyph from '@atlaskit/icon/svgs/lock-circle.svg';
import LockFilledGlyph from '@atlaskit/icon/svgs/lock-filled.svg';
import LockGlyph from '@atlaskit/icon/svgs/lock.svg';
import MarketplaceGlyph from '@atlaskit/icon/svgs/marketplace.svg';
import MediaServicesActualSizeGlyph from '@atlaskit/icon/svgs/media-services/actual-size.svg';
import MediaServicesAddCommentGlyph from '@atlaskit/icon/svgs/media-services/add-comment.svg';
import MediaServicesAnnotateGlyph from '@atlaskit/icon/svgs/media-services/annotate.svg';
import MediaServicesArrowGlyph from '@atlaskit/icon/svgs/media-services/arrow.svg';
import MediaServicesAudioGlyph from '@atlaskit/icon/svgs/media-services/audio.svg';
import MediaServicesBlurGlyph from '@atlaskit/icon/svgs/media-services/blur.svg';
import MediaServicesBrushGlyph from '@atlaskit/icon/svgs/media-services/brush.svg';
import MediaServicesButtonOptionGlyph from '@atlaskit/icon/svgs/media-services/button-option.svg';
import MediaServicesCodeGlyph from '@atlaskit/icon/svgs/media-services/code.svg';
import MediaServicesDocumentGlyph from '@atlaskit/icon/svgs/media-services/document.svg';
import MediaServicesFilterGlyph from '@atlaskit/icon/svgs/media-services/filter.svg';
import MediaServicesFitToPageGlyph from '@atlaskit/icon/svgs/media-services/fit-to-page.svg';
import MediaServicesFullScreenGlyph from '@atlaskit/icon/svgs/media-services/full-screen.svg';
import MediaServicesGridGlyph from '@atlaskit/icon/svgs/media-services/grid.svg';
import MediaServicesImageGlyph from '@atlaskit/icon/svgs/media-services/image.svg';
import MediaServicesLineThicknessGlyph from '@atlaskit/icon/svgs/media-services/line-thickness.svg';
import MediaServicesLineGlyph from '@atlaskit/icon/svgs/media-services/line.svg';
import MediaServicesNoImageGlyph from '@atlaskit/icon/svgs/media-services/no-image.svg';
import MediaServicesOpenMediaviewerGlyph from '@atlaskit/icon/svgs/media-services/open-mediaviewer.svg';
import MediaServicesOvalGlyph from '@atlaskit/icon/svgs/media-services/oval.svg';
import MediaServicesPdfGlyph from '@atlaskit/icon/svgs/media-services/pdf.svg';
import MediaServicesPreselectedGlyph from '@atlaskit/icon/svgs/media-services/preselected.svg';
import MediaServicesPresentationGlyph from '@atlaskit/icon/svgs/media-services/presentation.svg';
import MediaServicesRectangleGlyph from '@atlaskit/icon/svgs/media-services/rectangle.svg';
import MediaServicesScaleLargeGlyph from '@atlaskit/icon/svgs/media-services/scale-large.svg';
import MediaServicesScaleSmallGlyph from '@atlaskit/icon/svgs/media-services/scale-small.svg';
import MediaServicesSpreadsheetGlyph from '@atlaskit/icon/svgs/media-services/spreadsheet.svg';
import MediaServicesTextGlyph from '@atlaskit/icon/svgs/media-services/text.svg';
import MediaServicesUnknownGlyph from '@atlaskit/icon/svgs/media-services/unknown.svg';
import MediaServicesVideoGlyph from '@atlaskit/icon/svgs/media-services/video.svg';
import MediaServicesZipGlyph from '@atlaskit/icon/svgs/media-services/zip.svg';
import MediaServicesZoomInGlyph from '@atlaskit/icon/svgs/media-services/zoom-in.svg';
import MediaServicesZoomOutGlyph from '@atlaskit/icon/svgs/media-services/zoom-out.svg';
import MentionGlyph from '@atlaskit/icon/svgs/mention.svg';
import MenuExpandGlyph from '@atlaskit/icon/svgs/menu-expand.svg';
import MenuGlyph from '@atlaskit/icon/svgs/menu.svg';
import MoreVerticalGlyph from '@atlaskit/icon/svgs/more-vertical.svg';
import MoreGlyph from '@atlaskit/icon/svgs/more.svg';
import NotificationAllGlyph from '@atlaskit/icon/svgs/notification-all.svg';
import NotificationDirectGlyph from '@atlaskit/icon/svgs/notification-direct.svg';
import NotificationGlyph from '@atlaskit/icon/svgs/notification.svg';
import OfficeBuildingFilledGlyph from '@atlaskit/icon/svgs/office-building-filled.svg';
import OfficeBuildingGlyph from '@atlaskit/icon/svgs/office-building.svg';
import OpenGlyph from '@atlaskit/icon/svgs/open.svg';
import OverviewGlyph from '@atlaskit/icon/svgs/overview.svg';
import PageFilledGlyph from '@atlaskit/icon/svgs/page-filled.svg';
import PageGlyph from '@atlaskit/icon/svgs/page.svg';
import PdfGlyph from '@atlaskit/icon/svgs/pdf.svg';
import PeopleGroupGlyph from '@atlaskit/icon/svgs/people-group.svg';
import PeopleGlyph from '@atlaskit/icon/svgs/people.svg';
import PersonCircleGlyph from '@atlaskit/icon/svgs/person-circle.svg';
import PersonGlyph from '@atlaskit/icon/svgs/person.svg';
import PortfolioGlyph from '@atlaskit/icon/svgs/portfolio.svg';
import PreferencesGlyph from '@atlaskit/icon/svgs/preferences.svg';
import PremiumGlyph from '@atlaskit/icon/svgs/premium.svg';
import PresenceActiveGlyph from '@atlaskit/icon/svgs/presence-active.svg';
import PresenceBusyGlyph from '@atlaskit/icon/svgs/presence-busy.svg';
import PresenceUnavailableGlyph from '@atlaskit/icon/svgs/presence-unavailable.svg';
import QuestionCircleGlyph from '@atlaskit/icon/svgs/question-circle.svg';
import QuestionGlyph from '@atlaskit/icon/svgs/question.svg';
import QuestionsGlyph from '@atlaskit/icon/svgs/questions.svg';
import QueuesGlyph from '@atlaskit/icon/svgs/queues.svg';
import QuoteGlyph from '@atlaskit/icon/svgs/quote.svg';
import RadioGlyph from '@atlaskit/icon/svgs/radio.svg';
import RecentGlyph from '@atlaskit/icon/svgs/recent.svg';
import RedoGlyph from '@atlaskit/icon/svgs/redo.svg';
import RefreshGlyph from '@atlaskit/icon/svgs/refresh.svg';
import RetryGlyph from '@atlaskit/icon/svgs/retry.svg';
import RoadmapGlyph from '@atlaskit/icon/svgs/roadmap.svg';
import RoomMenuGlyph from '@atlaskit/icon/svgs/room-menu.svg';
import ScheduleFilledGlyph from '@atlaskit/icon/svgs/schedule-filled.svg';
import ScheduleGlyph from '@atlaskit/icon/svgs/schedule.svg';
import ScreenGlyph from '@atlaskit/icon/svgs/screen.svg';
import SearchGlyph from '@atlaskit/icon/svgs/search.svg';
import SelectClearGlyph from '@atlaskit/icon/svgs/select-clear.svg';
import SendGlyph from '@atlaskit/icon/svgs/send.svg';
import SettingsGlyph from '@atlaskit/icon/svgs/settings.svg';
import ShareGlyph from '@atlaskit/icon/svgs/share.svg';
import ShipGlyph from '@atlaskit/icon/svgs/ship.svg';
import ShortcutGlyph from '@atlaskit/icon/svgs/shortcut.svg';
import SignInGlyph from '@atlaskit/icon/svgs/sign-in.svg';
import SignOutGlyph from '@atlaskit/icon/svgs/sign-out.svg';
import StarFilledGlyph from '@atlaskit/icon/svgs/star-filled.svg';
import StarLargeGlyph from '@atlaskit/icon/svgs/star-large.svg';
import StarGlyph from '@atlaskit/icon/svgs/star.svg';
import StatusGlyph from '@atlaskit/icon/svgs/status.svg';
import SubtaskGlyph from '@atlaskit/icon/svgs/subtask.svg';
import SuitcaseGlyph from '@atlaskit/icon/svgs/suitcase.svg';
import SwitcherGlyph from '@atlaskit/icon/svgs/switcher.svg';
import TableGlyph from '@atlaskit/icon/svgs/table.svg';
import TaskGlyph from '@atlaskit/icon/svgs/task.svg';
import TrashGlyph from '@atlaskit/icon/svgs/trash.svg';
import TrayGlyph from '@atlaskit/icon/svgs/tray.svg';
import UndoGlyph from '@atlaskit/icon/svgs/undo.svg';
import UnlinkGlyph from '@atlaskit/icon/svgs/unlink.svg';
import UnlockCircleGlyph from '@atlaskit/icon/svgs/unlock-circle.svg';
import UnlockFilledGlyph from '@atlaskit/icon/svgs/unlock-filled.svg';
import UnlockGlyph from '@atlaskit/icon/svgs/unlock.svg';
import UploadGlyph from '@atlaskit/icon/svgs/upload.svg';
import UserAvatarCircleGlyph from '@atlaskit/icon/svgs/user-avatar-circle.svg';
import VidAudioMutedGlyph from '@atlaskit/icon/svgs/vid-audio-muted.svg';
import VidAudioOnGlyph from '@atlaskit/icon/svgs/vid-audio-on.svg';
import VidBackwardGlyph from '@atlaskit/icon/svgs/vid-backward.svg';
import VidCameraOffGlyph from '@atlaskit/icon/svgs/vid-camera-off.svg';
import VidCameraOnGlyph from '@atlaskit/icon/svgs/vid-camera-on.svg';
import VidConnectionCircleGlyph from '@atlaskit/icon/svgs/vid-connection-circle.svg';
import VidForwardGlyph from '@atlaskit/icon/svgs/vid-forward.svg';
import VidFullScreenOffGlyph from '@atlaskit/icon/svgs/vid-full-screen-off.svg';
import VidFullScreenOnGlyph from '@atlaskit/icon/svgs/vid-full-screen-on.svg';
import VidHangUpGlyph from '@atlaskit/icon/svgs/vid-hang-up.svg';
import VidHdCircleGlyph from '@atlaskit/icon/svgs/vid-hd-circle.svg';
import VidPauseGlyph from '@atlaskit/icon/svgs/vid-pause.svg';
import VidPlayGlyph from '@atlaskit/icon/svgs/vid-play.svg';
import VidRaisedHandGlyph from '@atlaskit/icon/svgs/vid-raised-hand.svg';
import VidShareScreenGlyph from '@atlaskit/icon/svgs/vid-share-screen.svg';
import VidSpeakingCircleGlyph from '@atlaskit/icon/svgs/vid-speaking-circle.svg';
import VidVolumeFullGlyph from '@atlaskit/icon/svgs/vid-volume-full.svg';
import VidVolumeHalfGlyph from '@atlaskit/icon/svgs/vid-volume-half.svg';
import VidVolumeMutedGlyph from '@atlaskit/icon/svgs/vid-volume-muted.svg';
import VideoCircleGlyph from '@atlaskit/icon/svgs/video-circle.svg';
import VideoFilledGlyph from '@atlaskit/icon/svgs/video-filled.svg';
import WarningGlyph from '@atlaskit/icon/svgs/warning.svg';
import WatchFilledGlyph from '@atlaskit/icon/svgs/watch-filled.svg';
import WatchGlyph from '@atlaskit/icon/svgs/watch.svg';
import WorldSmallGlyph from '@atlaskit/icon/svgs/world-small.svg';
import WorldGlyph from '@atlaskit/icon/svgs/world.svg';
import createIconComponent from './create-icon-component';

export const ActivityIcon = createIconComponent('ActivityIcon', ActivityGlyph);
export const AddCircleIcon = createIconComponent('AddCircleIcon', AddCircleGlyph);
export const AddItemIcon = createIconComponent('AddItemIcon', AddItemGlyph);
export const AddIcon = createIconComponent('AddIcon', AddGlyph);
export const AddonIcon = createIconComponent('AddonIcon', AddonGlyph);
export const AppAccessIcon = createIconComponent('AppAccessIcon', AppAccessGlyph);
export const AppSwitcherIcon = createIconComponent('AppSwitcherIcon', AppSwitcherGlyph);
export const ArrowDownCircleIcon = createIconComponent('ArrowDownCircleIcon', ArrowDownCircleGlyph);
export const ArrowDownIcon = createIconComponent('ArrowDownIcon', ArrowDownGlyph);
export const ArrowLeftCircleIcon = createIconComponent('ArrowLeftCircleIcon', ArrowLeftCircleGlyph);
export const ArrowLeftIcon = createIconComponent('ArrowLeftIcon', ArrowLeftGlyph);
export const ArrowRightCircleIcon = createIconComponent('ArrowRightCircleIcon', ArrowRightCircleGlyph);
export const ArrowRightIcon = createIconComponent('ArrowRightIcon', ArrowRightGlyph);
export const ArrowUpCircleIcon = createIconComponent('ArrowUpCircleIcon', ArrowUpCircleGlyph);
export const ArrowUpIcon = createIconComponent('ArrowUpIcon', ArrowUpGlyph);
export const AttachmentIcon = createIconComponent('AttachmentIcon', AttachmentGlyph);
export const AudioCircleIcon = createIconComponent('AudioCircleIcon', AudioCircleGlyph);
export const AudioIcon = createIconComponent('AudioIcon', AudioGlyph);
export const BacklogIcon = createIconComponent('BacklogIcon', BacklogGlyph);
export const BillingFilledIcon = createIconComponent('BillingFilledIcon', BillingFilledGlyph);
export const BillingIcon = createIconComponent('BillingIcon', BillingGlyph);
export const BitbucketBranchesIcon = createIconComponent('BitbucketBranchesIcon', BitbucketBranchesGlyph);
export const BitbucketBuildsIcon = createIconComponent('BitbucketBuildsIcon', BitbucketBuildsGlyph);
export const BitbucketCloneIcon = createIconComponent('BitbucketCloneIcon', BitbucketCloneGlyph);
export const BitbucketCommitsIcon = createIconComponent('BitbucketCommitsIcon', BitbucketCommitsGlyph);
export const BitbucketCompareIcon = createIconComponent('BitbucketCompareIcon', BitbucketCompareGlyph);
export const BitbucketForksIcon = createIconComponent('BitbucketForksIcon', BitbucketForksGlyph);
export const BitbucketOutputIcon = createIconComponent('BitbucketOutputIcon', BitbucketOutputGlyph);
export const BitbucketPipelinesIcon = createIconComponent('BitbucketPipelinesIcon', BitbucketPipelinesGlyph);
export const BitbucketPullrequestsIcon = createIconComponent('BitbucketPullrequestsIcon', BitbucketPullrequestsGlyph);
export const BitbucketReposIcon = createIconComponent('BitbucketReposIcon', BitbucketReposGlyph);
export const BitbucketSnippetsIcon = createIconComponent('BitbucketSnippetsIcon', BitbucketSnippetsGlyph);
export const BitbucketSourceIcon = createIconComponent('BitbucketSourceIcon', BitbucketSourceGlyph);
export const BoardIcon = createIconComponent('BoardIcon', BoardGlyph);
export const BookIcon = createIconComponent('BookIcon', BookGlyph);
export const BulletListIcon = createIconComponent('BulletListIcon', BulletListGlyph);
export const CalendarFilledIcon = createIconComponent('CalendarFilledIcon', CalendarFilledGlyph);
export const CalendarIcon = createIconComponent('CalendarIcon', CalendarGlyph);
export const CameraFilledIcon = createIconComponent('CameraFilledIcon', CameraFilledGlyph);
export const CameraRotateIcon = createIconComponent('CameraRotateIcon', CameraRotateGlyph);
export const CameraTakePictureIcon = createIconComponent('CameraTakePictureIcon', CameraTakePictureGlyph);
export const CameraIcon = createIconComponent('CameraIcon', CameraGlyph);
export const CanvasIcon = createIconComponent('CanvasIcon', CanvasGlyph);
export const CheckCircleOutlineIcon = createIconComponent('CheckCircleOutlineIcon', CheckCircleOutlineGlyph);
export const CheckCircleIcon = createIconComponent('CheckCircleIcon', CheckCircleGlyph);
export const CheckIcon = createIconComponent('CheckIcon', CheckGlyph);
export const CheckboxIndeterminateIcon = createIconComponent('CheckboxIndeterminateIcon', CheckboxIndeterminateGlyph);
export const CheckboxIcon = createIconComponent('CheckboxIcon', CheckboxGlyph);
export const ChevronDownCircleIcon = createIconComponent('ChevronDownCircleIcon', ChevronDownCircleGlyph);
export const ChevronDownIcon = createIconComponent('ChevronDownIcon', ChevronDownGlyph);
export const ChevronLeftCircleIcon = createIconComponent('ChevronLeftCircleIcon', ChevronLeftCircleGlyph);
export const ChevronLeftLargeIcon = createIconComponent('ChevronLeftLargeIcon', ChevronLeftLargeGlyph);
export const ChevronLeftIcon = createIconComponent('ChevronLeftIcon', ChevronLeftGlyph);
export const ChevronRightCircleIcon = createIconComponent('ChevronRightCircleIcon', ChevronRightCircleGlyph);
export const ChevronRightLargeIcon = createIconComponent('ChevronRightLargeIcon', ChevronRightLargeGlyph);
export const ChevronRightIcon = createIconComponent('ChevronRightIcon', ChevronRightGlyph);
export const ChevronUpCircleIcon = createIconComponent('ChevronUpCircleIcon', ChevronUpCircleGlyph);
export const ChevronUpIcon = createIconComponent('ChevronUpIcon', ChevronUpGlyph);
export const ChildIssuesIcon = createIconComponent('ChildIssuesIcon', ChildIssuesGlyph);
export const CodeIcon = createIconComponent('CodeIcon', CodeGlyph);
export const CommentIcon = createIconComponent('CommentIcon', CommentGlyph);
export const ComponentIcon = createIconComponent('ComponentIcon', ComponentGlyph);
export const CopyIcon = createIconComponent('CopyIcon', CopyGlyph);
export const CreditcardFilledIcon = createIconComponent('CreditcardFilledIcon', CreditcardFilledGlyph);
export const CreditcardIcon = createIconComponent('CreditcardIcon', CreditcardGlyph);
export const CrossCircleIcon = createIconComponent('CrossCircleIcon', CrossCircleGlyph);
export const CrossIcon = createIconComponent('CrossIcon', CrossGlyph);
export const DashboardIcon = createIconComponent('DashboardIcon', DashboardGlyph);
export const DecisionIcon = createIconComponent('DecisionIcon', DecisionGlyph);
export const DepartmentIcon = createIconComponent('DepartmentIcon', DepartmentGlyph);
export const DetailViewIcon = createIconComponent('DetailViewIcon', DetailViewGlyph);
export const DiscoverFilledIcon = createIconComponent('DiscoverFilledIcon', DiscoverFilledGlyph);
export const DiscoverIcon = createIconComponent('DiscoverIcon', DiscoverGlyph);
export const DocumentFilledIcon = createIconComponent('DocumentFilledIcon', DocumentFilledGlyph);
export const DocumentIcon = createIconComponent('DocumentIcon', DocumentGlyph);
export const DocumentsIcon = createIconComponent('DocumentsIcon', DocumentsGlyph);
export const DownloadIcon = createIconComponent('DownloadIcon', DownloadGlyph);
export const DragHandlerIcon = createIconComponent('DragHandlerIcon', DragHandlerGlyph);
export const DropboxIcon = createIconComponent('DropboxIcon', DropboxGlyph);
export const EditFilledIcon = createIconComponent('EditFilledIcon', EditFilledGlyph);
export const EditIcon = createIconComponent('EditIcon', EditGlyph);
export const EditorAddIcon = createIconComponent('EditorAddIcon', EditorAddGlyph);
export const EditorAddonIcon = createIconComponent('EditorAddonIcon', EditorAddonGlyph);
export const EditorAdvancedIcon = createIconComponent('EditorAdvancedIcon', EditorAdvancedGlyph);
export const EditorAlignCenterIcon = createIconComponent('EditorAlignCenterIcon', EditorAlignCenterGlyph);
export const EditorAlignImageCenterIcon = createIconComponent('EditorAlignImageCenterIcon', EditorAlignImageCenterGlyph);
export const EditorAlignImageLeftIcon = createIconComponent('EditorAlignImageLeftIcon', EditorAlignImageLeftGlyph);
export const EditorAlignImageRightIcon = createIconComponent('EditorAlignImageRightIcon', EditorAlignImageRightGlyph);
export const EditorAlignLeftIcon = createIconComponent('EditorAlignLeftIcon', EditorAlignLeftGlyph);
export const EditorAlignRightIcon = createIconComponent('EditorAlignRightIcon', EditorAlignRightGlyph);
export const EditorAttachmentIcon = createIconComponent('EditorAttachmentIcon', EditorAttachmentGlyph);
export const EditorBackgroundColorIcon = createIconComponent('EditorBackgroundColorIcon', EditorBackgroundColorGlyph);
export const EditorBoldIcon = createIconComponent('EditorBoldIcon', EditorBoldGlyph);
export const EditorBulletListIcon = createIconComponent('EditorBulletListIcon', EditorBulletListGlyph);
export const EditorCloseIcon = createIconComponent('EditorCloseIcon', EditorCloseGlyph);
export const EditorCodeIcon = createIconComponent('EditorCodeIcon', EditorCodeGlyph);
export const EditorCollapseIcon = createIconComponent('EditorCollapseIcon', EditorCollapseGlyph);
export const EditorDateIcon = createIconComponent('EditorDateIcon', EditorDateGlyph);
export const EditorDecisionIcon = createIconComponent('EditorDecisionIcon', EditorDecisionGlyph);
export const EditorDividerIcon = createIconComponent('EditorDividerIcon', EditorDividerGlyph);
export const EditorDoneIcon = createIconComponent('EditorDoneIcon', EditorDoneGlyph);
export const EditorEditIcon = createIconComponent('EditorEditIcon', EditorEditGlyph);
export const EditorEmojiIcon = createIconComponent('EditorEmojiIcon', EditorEmojiGlyph);
export const EditorErrorIcon = createIconComponent('EditorErrorIcon', EditorErrorGlyph);
export const EditorExpandIcon = createIconComponent('EditorExpandIcon', EditorExpandGlyph);
export const EditorFeedbackIcon = createIconComponent('EditorFeedbackIcon', EditorFeedbackGlyph);
export const EditorFileIcon = createIconComponent('EditorFileIcon', EditorFileGlyph);
export const EditorHelpIcon = createIconComponent('EditorHelpIcon', EditorHelpGlyph);
export const EditorHintIcon = createIconComponent('EditorHintIcon', EditorHintGlyph);
export const EditorHorizontalRuleIcon = createIconComponent('EditorHorizontalRuleIcon', EditorHorizontalRuleGlyph);
export const EditorImageBorderIcon = createIconComponent('EditorImageBorderIcon', EditorImageBorderGlyph);
export const EditorImageResizeIcon = createIconComponent('EditorImageResizeIcon', EditorImageResizeGlyph);
export const EditorImageIcon = createIconComponent('EditorImageIcon', EditorImageGlyph);
export const EditorIndentIcon = createIconComponent('EditorIndentIcon', EditorIndentGlyph);
export const EditorInfoIcon = createIconComponent('EditorInfoIcon', EditorInfoGlyph);
export const EditorItalicIcon = createIconComponent('EditorItalicIcon', EditorItalicGlyph);
export const EditorLayoutThreeEqualIcon = createIconComponent('EditorLayoutThreeEqualIcon', EditorLayoutThreeEqualGlyph);
export const EditorLayoutThreeWithSidebarsIcon = createIconComponent('EditorLayoutThreeWithSidebarsIcon', EditorLayoutThreeWithSidebarsGlyph);
export const EditorLayoutTwoEqualIcon = createIconComponent('EditorLayoutTwoEqualIcon', EditorLayoutTwoEqualGlyph);
export const EditorLayoutTwoLeftSidebarIcon = createIconComponent('EditorLayoutTwoLeftSidebarIcon', EditorLayoutTwoLeftSidebarGlyph);
export const EditorLayoutTwoRightSidebarIcon = createIconComponent('EditorLayoutTwoRightSidebarIcon', EditorLayoutTwoRightSidebarGlyph);
export const EditorLinkIcon = createIconComponent('EditorLinkIcon', EditorLinkGlyph);
export const EditorMediaCenterIcon = createIconComponent('EditorMediaCenterIcon', EditorMediaCenterGlyph);
export const EditorMediaFullWidthIcon = createIconComponent('EditorMediaFullWidthIcon', EditorMediaFullWidthGlyph);
export const EditorMediaWideIcon = createIconComponent('EditorMediaWideIcon', EditorMediaWideGlyph);
export const EditorMediaWrapLeftIcon = createIconComponent('EditorMediaWrapLeftIcon', EditorMediaWrapLeftGlyph);
export const EditorMediaWrapRightIcon = createIconComponent('EditorMediaWrapRightIcon', EditorMediaWrapRightGlyph);
export const EditorMentionIcon = createIconComponent('EditorMentionIcon', EditorMentionGlyph);
export const EditorMoreIcon = createIconComponent('EditorMoreIcon', EditorMoreGlyph);
export const EditorNoteIcon = createIconComponent('EditorNoteIcon', EditorNoteGlyph);
export const EditorNumberListIcon = createIconComponent('EditorNumberListIcon', EditorNumberListGlyph);
export const EditorOpenIcon = createIconComponent('EditorOpenIcon', EditorOpenGlyph);
export const EditorOutdentIcon = createIconComponent('EditorOutdentIcon', EditorOutdentGlyph);
export const EditorPanelIcon = createIconComponent('EditorPanelIcon', EditorPanelGlyph);
export const EditorPhotoIcon = createIconComponent('EditorPhotoIcon', EditorPhotoGlyph);
export const EditorQuoteIcon = createIconComponent('EditorQuoteIcon', EditorQuoteGlyph);
export const EditorRecentIcon = createIconComponent('EditorRecentIcon', EditorRecentGlyph);
export const EditorRedoIcon = createIconComponent('EditorRedoIcon', EditorRedoGlyph);
export const EditorRemoveIcon = createIconComponent('EditorRemoveIcon', EditorRemoveGlyph);
export const EditorSearchIcon = createIconComponent('EditorSearchIcon', EditorSearchGlyph);
export const EditorSettingsIcon = createIconComponent('EditorSettingsIcon', EditorSettingsGlyph);
export const EditorStrikethroughIcon = createIconComponent('EditorStrikethroughIcon', EditorStrikethroughGlyph);
export const EditorSuccessIcon = createIconComponent('EditorSuccessIcon', EditorSuccessGlyph);
export const EditorTableDisplayOptionsIcon = createIconComponent('EditorTableDisplayOptionsIcon', EditorTableDisplayOptionsGlyph);
export const EditorTableIcon = createIconComponent('EditorTableIcon', EditorTableGlyph);
export const EditorTaskIcon = createIconComponent('EditorTaskIcon', EditorTaskGlyph);
export const EditorTextColorIcon = createIconComponent('EditorTextColorIcon', EditorTextColorGlyph);
export const EditorTextStyleIcon = createIconComponent('EditorTextStyleIcon', EditorTextStyleGlyph);
export const EditorUnderlineIcon = createIconComponent('EditorUnderlineIcon', EditorUnderlineGlyph);
export const EditorUndoIcon = createIconComponent('EditorUndoIcon', EditorUndoGlyph);
export const EditorUnlinkIcon = createIconComponent('EditorUnlinkIcon', EditorUnlinkGlyph);
export const EditorWarningIcon = createIconComponent('EditorWarningIcon', EditorWarningGlyph);
export const EmailIcon = createIconComponent('EmailIcon', EmailGlyph);
export const EmojiActivityIcon = createIconComponent('EmojiActivityIcon', EmojiActivityGlyph);
export const EmojiAtlassianIcon = createIconComponent('EmojiAtlassianIcon', EmojiAtlassianGlyph);
export const EmojiCustomIcon = createIconComponent('EmojiCustomIcon', EmojiCustomGlyph);
export const EmojiEmojiIcon = createIconComponent('EmojiEmojiIcon', EmojiEmojiGlyph);
export const EmojiFlagsIcon = createIconComponent('EmojiFlagsIcon', EmojiFlagsGlyph);
export const EmojiFoodIcon = createIconComponent('EmojiFoodIcon', EmojiFoodGlyph);
export const EmojiFrequentIcon = createIconComponent('EmojiFrequentIcon', EmojiFrequentGlyph);
export const EmojiKeyboardIcon = createIconComponent('EmojiKeyboardIcon', EmojiKeyboardGlyph);
export const EmojiNatureIcon = createIconComponent('EmojiNatureIcon', EmojiNatureGlyph);
export const EmojiObjectsIcon = createIconComponent('EmojiObjectsIcon', EmojiObjectsGlyph);
export const EmojiPeopleIcon = createIconComponent('EmojiPeopleIcon', EmojiPeopleGlyph);
export const EmojiProductivityIcon = createIconComponent('EmojiProductivityIcon', EmojiProductivityGlyph);
export const EmojiSymbolsIcon = createIconComponent('EmojiSymbolsIcon', EmojiSymbolsGlyph);
export const EmojiTravelIcon = createIconComponent('EmojiTravelIcon', EmojiTravelGlyph);
export const EmojiAddIcon = createIconComponent('EmojiAddIcon', EmojiAddGlyph);
export const EmojiIcon = createIconComponent('EmojiIcon', EmojiGlyph);
export const ErrorIcon = createIconComponent('ErrorIcon', ErrorGlyph);
export const ExportIcon = createIconComponent('ExportIcon', ExportGlyph);
export const FeedbackIcon = createIconComponent('FeedbackIcon', FeedbackGlyph);
export const FileIcon = createIconComponent('FileIcon', FileGlyph);
export const FilterIcon = createIconComponent('FilterIcon', FilterGlyph);
export const FlagFilledIcon = createIconComponent('FlagFilledIcon', FlagFilledGlyph);
export const FolderFilledIcon = createIconComponent('FolderFilledIcon', FolderFilledGlyph);
export const FolderIcon = createIconComponent('FolderIcon', FolderGlyph);
export const FollowersIcon = createIconComponent('FollowersIcon', FollowersGlyph);
export const FollowingIcon = createIconComponent('FollowingIcon', FollowingGlyph);
export const GoogledriveIcon = createIconComponent('GoogledriveIcon', GoogledriveGlyph);
export const GraphBarIcon = createIconComponent('GraphBarIcon', GraphBarGlyph);
export const GraphLineIcon = createIconComponent('GraphLineIcon', GraphLineGlyph);
export const GsuiteIcon = createIconComponent('GsuiteIcon', GsuiteGlyph);
export const HighlightsIcon = createIconComponent('HighlightsIcon', HighlightsGlyph);
export const HipchatAudioOnlyIcon = createIconComponent('HipchatAudioOnlyIcon', HipchatAudioOnlyGlyph);
export const HipchatChevronDoubleDownIcon = createIconComponent('HipchatChevronDoubleDownIcon', HipchatChevronDoubleDownGlyph);
export const HipchatChevronDoubleUpIcon = createIconComponent('HipchatChevronDoubleUpIcon', HipchatChevronDoubleUpGlyph);
export const HipchatChevronDownIcon = createIconComponent('HipchatChevronDownIcon', HipchatChevronDownGlyph);
export const HipchatChevronUpIcon = createIconComponent('HipchatChevronUpIcon', HipchatChevronUpGlyph);
export const HipchatDialOutIcon = createIconComponent('HipchatDialOutIcon', HipchatDialOutGlyph);
export const HipchatLobbyIcon = createIconComponent('HipchatLobbyIcon', HipchatLobbyGlyph);
export const HipchatMediaAttachmentCountIcon = createIconComponent('HipchatMediaAttachmentCountIcon', HipchatMediaAttachmentCountGlyph);
export const HipchatOutgoingSoundIcon = createIconComponent('HipchatOutgoingSoundIcon', HipchatOutgoingSoundGlyph);
export const HipchatSdVideoIcon = createIconComponent('HipchatSdVideoIcon', HipchatSdVideoGlyph);
export const HomeCircleIcon = createIconComponent('HomeCircleIcon', HomeCircleGlyph);
export const HomeFilledIcon = createIconComponent('HomeFilledIcon', HomeFilledGlyph);
export const ImageBorderIcon = createIconComponent('ImageBorderIcon', ImageBorderGlyph);
export const ImageResizeIcon = createIconComponent('ImageResizeIcon', ImageResizeGlyph);
export const ImageIcon = createIconComponent('ImageIcon', ImageGlyph);
export const InfoIcon = createIconComponent('InfoIcon', InfoGlyph);
export const InviteTeamIcon = createIconComponent('InviteTeamIcon', InviteTeamGlyph);
export const IssueRaiseIcon = createIconComponent('IssueRaiseIcon', IssueRaiseGlyph);
export const IssueIcon = createIconComponent('IssueIcon', IssueGlyph);
export const IssuesIcon = createIconComponent('IssuesIcon', IssuesGlyph);
export const JiraCaptureIcon = createIconComponent('JiraCaptureIcon', JiraCaptureGlyph);
export const JiraFailedBuildStatusIcon = createIconComponent('JiraFailedBuildStatusIcon', JiraFailedBuildStatusGlyph);
export const JiraLabsIcon = createIconComponent('JiraLabsIcon', JiraLabsGlyph);
export const JiraTestSessionIcon = createIconComponent('JiraTestSessionIcon', JiraTestSessionGlyph);
export const LabelIcon = createIconComponent('LabelIcon', LabelGlyph);
export const LightbulbFilledIcon = createIconComponent('LightbulbFilledIcon', LightbulbFilledGlyph);
export const LightbulbIcon = createIconComponent('LightbulbIcon', LightbulbGlyph);
export const LikeIcon = createIconComponent('LikeIcon', LikeGlyph);
export const LinkFilledIcon = createIconComponent('LinkFilledIcon', LinkFilledGlyph);
export const LinkIcon = createIconComponent('LinkIcon', LinkGlyph);
export const ListIcon = createIconComponent('ListIcon', ListGlyph);
export const LocationIcon = createIconComponent('LocationIcon', LocationGlyph);
export const LockCircleIcon = createIconComponent('LockCircleIcon', LockCircleGlyph);
export const LockFilledIcon = createIconComponent('LockFilledIcon', LockFilledGlyph);
export const LockIcon = createIconComponent('LockIcon', LockGlyph);
export const MarketplaceIcon = createIconComponent('MarketplaceIcon', MarketplaceGlyph);
export const MediaServicesActualSizeIcon = createIconComponent('MediaServicesActualSizeIcon', MediaServicesActualSizeGlyph);
export const MediaServicesAddCommentIcon = createIconComponent('MediaServicesAddCommentIcon', MediaServicesAddCommentGlyph);
export const MediaServicesAnnotateIcon = createIconComponent('MediaServicesAnnotateIcon', MediaServicesAnnotateGlyph);
export const MediaServicesArrowIcon = createIconComponent('MediaServicesArrowIcon', MediaServicesArrowGlyph);
export const MediaServicesAudioIcon = createIconComponent('MediaServicesAudioIcon', MediaServicesAudioGlyph);
export const MediaServicesBlurIcon = createIconComponent('MediaServicesBlurIcon', MediaServicesBlurGlyph);
export const MediaServicesBrushIcon = createIconComponent('MediaServicesBrushIcon', MediaServicesBrushGlyph);
export const MediaServicesButtonOptionIcon = createIconComponent('MediaServicesButtonOptionIcon', MediaServicesButtonOptionGlyph);
export const MediaServicesCodeIcon = createIconComponent('MediaServicesCodeIcon', MediaServicesCodeGlyph);
export const MediaServicesDocumentIcon = createIconComponent('MediaServicesDocumentIcon', MediaServicesDocumentGlyph);
export const MediaServicesFilterIcon = createIconComponent('MediaServicesFilterIcon', MediaServicesFilterGlyph);
export const MediaServicesFitToPageIcon = createIconComponent('MediaServicesFitToPageIcon', MediaServicesFitToPageGlyph);
export const MediaServicesFullScreenIcon = createIconComponent('MediaServicesFullScreenIcon', MediaServicesFullScreenGlyph);
export const MediaServicesGridIcon = createIconComponent('MediaServicesGridIcon', MediaServicesGridGlyph);
export const MediaServicesImageIcon = createIconComponent('MediaServicesImageIcon', MediaServicesImageGlyph);
export const MediaServicesLineThicknessIcon = createIconComponent('MediaServicesLineThicknessIcon', MediaServicesLineThicknessGlyph);
export const MediaServicesLineIcon = createIconComponent('MediaServicesLineIcon', MediaServicesLineGlyph);
export const MediaServicesNoImageIcon = createIconComponent('MediaServicesNoImageIcon', MediaServicesNoImageGlyph);
export const MediaServicesOpenMediaviewerIcon = createIconComponent('MediaServicesOpenMediaviewerIcon', MediaServicesOpenMediaviewerGlyph);
export const MediaServicesOvalIcon = createIconComponent('MediaServicesOvalIcon', MediaServicesOvalGlyph);
export const MediaServicesPdfIcon = createIconComponent('MediaServicesPdfIcon', MediaServicesPdfGlyph);
export const MediaServicesPreselectedIcon = createIconComponent('MediaServicesPreselectedIcon', MediaServicesPreselectedGlyph);
export const MediaServicesPresentationIcon = createIconComponent('MediaServicesPresentationIcon', MediaServicesPresentationGlyph);
export const MediaServicesRectangleIcon = createIconComponent('MediaServicesRectangleIcon', MediaServicesRectangleGlyph);
export const MediaServicesScaleLargeIcon = createIconComponent('MediaServicesScaleLargeIcon', MediaServicesScaleLargeGlyph);
export const MediaServicesScaleSmallIcon = createIconComponent('MediaServicesScaleSmallIcon', MediaServicesScaleSmallGlyph);
export const MediaServicesSpreadsheetIcon = createIconComponent('MediaServicesSpreadsheetIcon', MediaServicesSpreadsheetGlyph);
export const MediaServicesTextIcon = createIconComponent('MediaServicesTextIcon', MediaServicesTextGlyph);
export const MediaServicesUnknownIcon = createIconComponent('MediaServicesUnknownIcon', MediaServicesUnknownGlyph);
export const MediaServicesVideoIcon = createIconComponent('MediaServicesVideoIcon', MediaServicesVideoGlyph);
export const MediaServicesZipIcon = createIconComponent('MediaServicesZipIcon', MediaServicesZipGlyph);
export const MediaServicesZoomInIcon = createIconComponent('MediaServicesZoomInIcon', MediaServicesZoomInGlyph);
export const MediaServicesZoomOutIcon = createIconComponent('MediaServicesZoomOutIcon', MediaServicesZoomOutGlyph);
export const MentionIcon = createIconComponent('MentionIcon', MentionGlyph);
export const MenuExpandIcon = createIconComponent('MenuExpandIcon', MenuExpandGlyph);
export const MenuIcon = createIconComponent('MenuIcon', MenuGlyph);
export const MoreVerticalIcon = createIconComponent('MoreVerticalIcon', MoreVerticalGlyph);
export const MoreIcon = createIconComponent('MoreIcon', MoreGlyph);
export const NotificationAllIcon = createIconComponent('NotificationAllIcon', NotificationAllGlyph);
export const NotificationDirectIcon = createIconComponent('NotificationDirectIcon', NotificationDirectGlyph);
export const NotificationIcon = createIconComponent('NotificationIcon', NotificationGlyph);
export const OfficeBuildingFilledIcon = createIconComponent('OfficeBuildingFilledIcon', OfficeBuildingFilledGlyph);
export const OfficeBuildingIcon = createIconComponent('OfficeBuildingIcon', OfficeBuildingGlyph);
export const OpenIcon = createIconComponent('OpenIcon', OpenGlyph);
export const OverviewIcon = createIconComponent('OverviewIcon', OverviewGlyph);
export const PageFilledIcon = createIconComponent('PageFilledIcon', PageFilledGlyph);
export const PageIcon = createIconComponent('PageIcon', PageGlyph);
export const PdfIcon = createIconComponent('PdfIcon', PdfGlyph);
export const PeopleGroupIcon = createIconComponent('PeopleGroupIcon', PeopleGroupGlyph);
export const PeopleIcon = createIconComponent('PeopleIcon', PeopleGlyph);
export const PersonCircleIcon = createIconComponent('PersonCircleIcon', PersonCircleGlyph);
export const PersonIcon = createIconComponent('PersonIcon', PersonGlyph);
export const PortfolioIcon = createIconComponent('PortfolioIcon', PortfolioGlyph);
export const PreferencesIcon = createIconComponent('PreferencesIcon', PreferencesGlyph);
export const PremiumIcon = createIconComponent('PremiumIcon', PremiumGlyph);
export const PresenceActiveIcon = createIconComponent('PresenceActiveIcon', PresenceActiveGlyph);
export const PresenceBusyIcon = createIconComponent('PresenceBusyIcon', PresenceBusyGlyph);
export const PresenceUnavailableIcon = createIconComponent('PresenceUnavailableIcon', PresenceUnavailableGlyph);
export const QuestionCircleIcon = createIconComponent('QuestionCircleIcon', QuestionCircleGlyph);
export const QuestionIcon = createIconComponent('QuestionIcon', QuestionGlyph);
export const QuestionsIcon = createIconComponent('QuestionsIcon', QuestionsGlyph);
export const QueuesIcon = createIconComponent('QueuesIcon', QueuesGlyph);
export const QuoteIcon = createIconComponent('QuoteIcon', QuoteGlyph);
export const RadioIcon = createIconComponent('RadioIcon', RadioGlyph);
export const RecentIcon = createIconComponent('RecentIcon', RecentGlyph);
export const RedoIcon = createIconComponent('RedoIcon', RedoGlyph);
export const RefreshIcon = createIconComponent('RefreshIcon', RefreshGlyph);
export const RetryIcon = createIconComponent('RetryIcon', RetryGlyph);
export const RoadmapIcon = createIconComponent('RoadmapIcon', RoadmapGlyph);
export const RoomMenuIcon = createIconComponent('RoomMenuIcon', RoomMenuGlyph);
export const ScheduleFilledIcon = createIconComponent('ScheduleFilledIcon', ScheduleFilledGlyph);
export const ScheduleIcon = createIconComponent('ScheduleIcon', ScheduleGlyph);
export const ScreenIcon = createIconComponent('ScreenIcon', ScreenGlyph);
export const SearchIcon = createIconComponent('SearchIcon', SearchGlyph);
export const SelectClearIcon = createIconComponent('SelectClearIcon', SelectClearGlyph);
export const SendIcon = createIconComponent('SendIcon', SendGlyph);
export const SettingsIcon = createIconComponent('SettingsIcon', SettingsGlyph);
export const ShareIcon = createIconComponent('ShareIcon', ShareGlyph);
export const ShipIcon = createIconComponent('ShipIcon', ShipGlyph);
export const ShortcutIcon = createIconComponent('ShortcutIcon', ShortcutGlyph);
export const SignInIcon = createIconComponent('SignInIcon', SignInGlyph);
export const SignOutIcon = createIconComponent('SignOutIcon', SignOutGlyph);
export const StarFilledIcon = createIconComponent('StarFilledIcon', StarFilledGlyph);
export const StarLargeIcon = createIconComponent('StarLargeIcon', StarLargeGlyph);
export const StarIcon = createIconComponent('StarIcon', StarGlyph);
export const StatusIcon = createIconComponent('StatusIcon', StatusGlyph);
export const SubtaskIcon = createIconComponent('SubtaskIcon', SubtaskGlyph);
export const SuitcaseIcon = createIconComponent('SuitcaseIcon', SuitcaseGlyph);
export const SwitcherIcon = createIconComponent('SwitcherIcon', SwitcherGlyph);
export const TableIcon = createIconComponent('TableIcon', TableGlyph);
export const TaskIcon = createIconComponent('TaskIcon', TaskGlyph);
export const TrashIcon = createIconComponent('TrashIcon', TrashGlyph);
export const TrayIcon = createIconComponent('TrayIcon', TrayGlyph);
export const UndoIcon = createIconComponent('UndoIcon', UndoGlyph);
export const UnlinkIcon = createIconComponent('UnlinkIcon', UnlinkGlyph);
export const UnlockCircleIcon = createIconComponent('UnlockCircleIcon', UnlockCircleGlyph);
export const UnlockFilledIcon = createIconComponent('UnlockFilledIcon', UnlockFilledGlyph);
export const UnlockIcon = createIconComponent('UnlockIcon', UnlockGlyph);
export const UploadIcon = createIconComponent('UploadIcon', UploadGlyph);
export const UserAvatarCircleIcon = createIconComponent('UserAvatarCircleIcon', UserAvatarCircleGlyph);
export const VidAudioMutedIcon = createIconComponent('VidAudioMutedIcon', VidAudioMutedGlyph);
export const VidAudioOnIcon = createIconComponent('VidAudioOnIcon', VidAudioOnGlyph);
export const VidBackwardIcon = createIconComponent('VidBackwardIcon', VidBackwardGlyph);
export const VidCameraOffIcon = createIconComponent('VidCameraOffIcon', VidCameraOffGlyph);
export const VidCameraOnIcon = createIconComponent('VidCameraOnIcon', VidCameraOnGlyph);
export const VidConnectionCircleIcon = createIconComponent('VidConnectionCircleIcon', VidConnectionCircleGlyph);
export const VidForwardIcon = createIconComponent('VidForwardIcon', VidForwardGlyph);
export const VidFullScreenOffIcon = createIconComponent('VidFullScreenOffIcon', VidFullScreenOffGlyph);
export const VidFullScreenOnIcon = createIconComponent('VidFullScreenOnIcon', VidFullScreenOnGlyph);
export const VidHangUpIcon = createIconComponent('VidHangUpIcon', VidHangUpGlyph);
export const VidHdCircleIcon = createIconComponent('VidHdCircleIcon', VidHdCircleGlyph);
export const VidPauseIcon = createIconComponent('VidPauseIcon', VidPauseGlyph);
export const VidPlayIcon = createIconComponent('VidPlayIcon', VidPlayGlyph);
export const VidRaisedHandIcon = createIconComponent('VidRaisedHandIcon', VidRaisedHandGlyph);
export const VidShareScreenIcon = createIconComponent('VidShareScreenIcon', VidShareScreenGlyph);
export const VidSpeakingCircleIcon = createIconComponent('VidSpeakingCircleIcon', VidSpeakingCircleGlyph);
export const VidVolumeFullIcon = createIconComponent('VidVolumeFullIcon', VidVolumeFullGlyph);
export const VidVolumeHalfIcon = createIconComponent('VidVolumeHalfIcon', VidVolumeHalfGlyph);
export const VidVolumeMutedIcon = createIconComponent('VidVolumeMutedIcon', VidVolumeMutedGlyph);
export const VideoCircleIcon = createIconComponent('VideoCircleIcon', VideoCircleGlyph);
export const VideoFilledIcon = createIconComponent('VideoFilledIcon', VideoFilledGlyph);
export const WarningIcon = createIconComponent('WarningIcon', WarningGlyph);
export const WatchFilledIcon = createIconComponent('WatchFilledIcon', WatchFilledGlyph);
export const WatchIcon = createIconComponent('WatchIcon', WatchGlyph);
export const WorldSmallIcon = createIconComponent('WorldSmallIcon', WorldSmallGlyph);
export const WorldIcon = createIconComponent('WorldIcon', WorldGlyph);
